### ISSUE TITLE
Compile error when `MCUBOOT_DIRECT_XIP_REVERT` is defined

### ISSUE THREAD

**Issue by RcColes** [mcu-tools/mcuboot#1028]
`boot/bootutil/loader.c:2292` and `boot/bootutil/loader.c:2213` refer to the variable `slot`, that was renamed in ccaf7f88 to `active_slot`. Looks like just a rename to fix it, though I guess this means we don't have test coverage for `MCUBOOT_DIRECT_XIP_REVERT`.

**Comment by nvlsianpu** [comment]
There is PR: https://github.com/mcu-tools/mcuboot/pull/1019 for cover missing verification part.
