### ISSUE TITLE
signed_images.md seems to be outdated 

### ISSUE THREAD

**Issue by FrancescoSer** [mcu-tools/mcuboot#1180]
In the documentation file index.md, line 42, there is currently this sentence:

> There is also a document about **[signed images](signed_images.md) that is out of date.**  You should use `imgtool.py` instead of these documents.

**Is this actually the case?**

---

This document is still currently referenced in the following instances:.
* imgtool.md, line 6:
> Using this script should be preferred to the manual steps described in `doc/signed_images.md`.

* imgtool.md, line 39:
> follow the instructions in `doc/signed_images.md` to generate the key file

* encrypted_images.md, line 159
> * If using RSA-OAEP, generate a keypair following steps similar to those described in [signed_images](signed_images.md) to create RSA keys.
> * If using ECIES-P256, generate a keypair following steps similar to those described in [signed_images](signed_images.md) to create ECDSA256 keys.

* design.md line 1022
> For information on embedding public keys in the bootloader, as well as producing signed images, see: [signed_images](signed_images.md).

---

It seems to me that either:
* signed_images.md is outdated and not relevant anymore. The doc file should then be removed and all these mentions should be updated
* signed_images.md is outdated but it can be updated and it would still be relevant if updated.
* signed_images.md is not outdated, and the sentence written in index.md should be removed.

**Comment by d3zd3z** [comment]
This still needs to be fixed.

**Comment by FrancescoSer** [comment]
I guess this still need to be fixed
