### ISSUE TITLE
Port imgtool to cbor2

### ISSUE THREAD

**Issue by rossburton** [mcu-tools/mcuboot#1189]
python-cbor is dead, the last release was 1.0.0, in 2016: https://pypi.org/project/cbor/#history

However, python-cbor2 has the same functionality and is still active, last released in October 2021: https://pypi.org/project/cbor2/#history

Please consider the trivial port from `cbor` to `cbor2`.

**Comment by d3zd3z** [comment]
Unsure whether to call this a bug or an enhancement. This definitely should be done, though.
