### ISSUE TITLE
Possible size overflow for header block size in image encryption

### ISSUE THREAD

**Issue by kvaellning** [mcu-tools/mcuboot#1191]
**Issue:**

I am using MCUboot with Zephyr, and set a header size of 0x1000. In `loader:boot_copy_region`, this leads to a chunk size of 0x400 (buffer size). If on start of the image (`loader.c:907`), this leads to a silent overflow in `blk_sz` on line 910.

Interesting code:
`blk_sz = chunk_sz - hdr->ih_hdr_size; // chunk_sz = 0x400; hdr->ih_hdr_size = 0x1000`.

**Suggested fix:**

1. Check for this overflow, return `BOOT_EBADARGS`
2. imgtool should check for meaningful values of the header size.

**Comment by nvlsianpu** [comment]
@kvaellning Is so big header something that you needed? Current code support header up to 1024 B size.
If this is just a bug hunting then I would go with fixes you suggested.

**Comment by kvaellning** [comment]
This was basically a misconfiguration on my side, and I was curious why my image was corrupted without seeing an error. For my application, I can live with smaller header sizes (which I now use). I‘ll provide a pull request with the suggested fixes by tomorrow.

**Comment by d3zd3z** [comment]
Adding a check is a good first step. The code could be reworked to not require that the header fit into the first block, though.

The header size is determined by the number of IRQs on the SoC (at least for Arm). The number of IRQs in the vector table determines the required alignment of the image (hence the size of the header). 256 IRQs isn't that uncommon, and I could see needing more.

**Comment by nvlsianpu** [comment]
^^ I'm looking at better solution.
