### ISSUE TITLE
RSA decryption key can't be loaded due to mbedtls_rsa_rsaes_oaep_decrypt() error

### ISSUE THREAD

**Issue by nvlsianpu** [mcu-tools/mcuboot#1200]
I tested encryption with zephyr-rtos and mbedtls 3.0.0

west build -d build/xd -b nrf52840dk_nrf52840 bootloader/mcuboot/boot/zephyr -- -DCONFIG_BOOT_ENCRYPT_RSA=y -DCONFIG_BOOT_BOOTSTRAP=y

RSA decryption is failing due to error in encryption key decryption.
call to mbedtls_rsa_rsaes_oaep_decrypt() from boot_enc_decrypt() returns erorcode -0x4310

This is regression in compression to mbedtls 2.7.0 usage

**Comment by d3zd3z** [comment]
See #1203 to track adding sim support to catch this kind of issue earlier.
