### ISSUE TITLE
Idea: Scratch Partition in RAM

### ISSUE THREAD

**Issue by biglben** [mcu-tools/mcuboot#1224]
Hi
Are there plans to add an option to move the scratch partition to RAM?
I think it would be faster to upgrade and also increases the number of upgrades because of less flash wearout

Are there some important points why this isn't supported yet?

**Comment by utzig** [comment]
> Hi Are there plans to add an option to move the scratch partition to RAM? I think it would be faster to upgrade and also increases the number of upgrades because of less flash wearout
> 
> Are there some important points why this isn't supported yet?

What if the system is reset in the middle of the upgrade?

**Comment by biglben** [comment]
That makes sense, thank you
