### ISSUE TITLE
sim: warning: field is never read: `flag_help`

### ISSUE THREAD

**Issue by nvlsianpu** [mcu-tools/mcuboot#1244]
ci is failing on sim because of:

```
warning: field is never read: `flag_help`
  --> sim/src/lib.rs:55:5
   |
55 |     flag_help: bool,
   |     ^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default
```
ref: https://github.com/mcu-tools/mcuboot/runs/4536003262?check_suite_focus=true

This happens not for each commit for some reason.
It happened after https://github.com/mcu-tools/mcuboot/pull/1242 has been merged for instance.

**Comment by utzig** [comment]
Might have started happening due to a Rust upgrade, should be fixed by #1245
