### ISSUE TITLE
Image integrity is not calculated after upgrade using OVERWRITE mode

### ISSUE THREAD

**Issue by romanjoe** [mcu-tools/mcuboot#1307]
We have following observation in our case, where we have upgrade image located in external memory:

If we have some power glitches or short term voltage drawdowns while copying from UPGRADE to BOOT slot we sometimes have a case where following read/write operation from external flash ends up successful, but data is invalid.

In this case we have successful upgrade via OVERWRITE, then upgrade image is discarded. Image in BOOT slot is invalid however, but this fact would be revealed only after reset on validation stage.

Question is the following - is it possible to at least verify image hash of firmware copied to BOOT slot (or another type of integrity verification) in MCUBoot right after successful upgrade operation fact, so we can be sure image integrity is correct before discarding upgrade image?

**Comment by d3zd3z** [comment]
As you mention, I don't think it does this currently, but could possibly should be added. However, if you are seeing incorrect behavior (there is a time window during upgrade where the upgrade image is discarded, but the upgrade didn't finish) then that would be a higher priority issue.
