### ISSUE TITLE
zephyr: booting address incorrect in ram-load mode

### ISSUE THREAD

**Issue by kctan0805** [mcu-tools/mcuboot#1330]
In this function:
https://github.com/mcu-tools/mcuboot/blob/749bc31c8bf59ebfb2a5cc270ffbac894e380b6e/boot/zephyr/main.c#L297

program jump to the flash address + header size of this image. It should be jump to the loading address + header size of this image.

This is how I fixed:

```
#if defined(MCUBOOT_RAM_LOAD)
    start = (void *)(rsp->br_hdr->ih_load_addr + rsp->br_hdr->ih_hdr_size);
#else
    uintptr_t flash_base;
    int rc;

    rc = flash_device_base(rsp->br_flash_dev_id, &flash_base);
    assert(rc == 0);

    start = (void *)(flash_base + rsp->br_image_off +
                     rsp->br_hdr->ih_hdr_size);
#endif

```
Should I submit a PR?

**Comment by d3zd3z** [comment]
Sure, a PR would be appreciated.
