### ISSUE TITLE
ECIES not working with AES 256 keys

### ISSUE THREAD

**Issue by michaelthomasj** [mcu-tools/mcuboot#1348]
The signing script seems to hardcode the AES key length to 128 bits when using ECIES: 
https://github.com/mcu-tools/mcuboot/blob/93d02179b32056320deaac7919247173793febbe/scripts/imgtool/image.py#L287
The HKDF length is 48 bytes there: 16 bytes for the AES key and 32 bytes for the MAC. That is correct for AES-128. 
The HKDF should be 64; 32 bytes each for AES and MAC. The line after that should also be updated to use the first 32 bytes for the AES key.

**Comment by d3zd3z** [comment]
I'm not sure the rest of the code has been tested with anything other than AES-128. It'd be worth fixing if we add support for a larger cipher, maybe even earlier, since it would not be obvious this needs to be fixed.

**Comment by michaelthomasj** [comment]
I agree that since we only support ECIES-P256 and RSA-OAEP 2K/3K, AES 128 is sufficient. However, if MCUboot plans to support EC-P384 then we would have to support AES 256 or 192. 
Since we do not support AES 256, we should remove the "--encrypt-keylen" option from imgtool since it lets the user select AES 128 or 256 but then it just implements AES 128 which is misleading.
