### ISSUE TITLE
imgtool incorrect trailer added for confirmed image

### ISSUE THREAD

**Issue by DerekSnell** [mcu-tools/mcuboot#1390]
Hello,

Using Zephyr we found an issue using imgtool to generate a signed and confirmed image for MCUboot.  The issue occurs with more recent versions of imgtool, and MCUboot is not able to boot the image.  We found reverting to an older release v1.7.2 of imgtool resolves this issue.  The issue is also avoided if the image generated is not confirmed.  It appears to be an issue with the padding/trailer generated by imgtool.  More details on replicating this issue, and the errors booting are posted at this [Zephyr GitHub issue](https://github.com/zephyrproject-rtos/zephyr/issues/46414).  

Attached are two HEX files I played with. The first file Fails.v190.zephyr.unsigned.confirmed.hex was generated using the posted steps provided with imgtool v1.9.0. This file appears to have the improper padding at the end of the slot image.

The 2nd file Succeeds.v190.zephyr.modified.confirmed.hex will boot. I manually modified this HEX file, by copying the trailer generated with imgtool v1.7.2, and pasting in this file. You can do a diff on these files to see what I changed. 

[HEX_Files.zip](https://github.com/mcu-tools/mcuboot/files/8920962/HEX_Files.zip)

**Comment by d3zd3z** [comment]
Is it possible to use a debugger to determine where the bus fault is coming from?
