### ISSUE TITLE
Support for multiple load strategies

### ISSUE THREAD

**Issue by PetrBuchtaNXP** [mcu-tools/mcuboot#1392]
Hi, I have a platform that consist of 4 firmware images. One bootable application that runs from flash (XIP) and other three radio images that are loaded by the main application from flash to ram.

I'm using mcuboot 1.9.0 and I'm missing to be able to **configure each image individually for its image swap strategy**. The first image is linked to a certain flash location, so the swap mechanism is needed. However, since the other radio images are of load-to-ram nature, there is no swap technically required. I'm aware this would need some sort of flag which A/B location is the active one.

Is this something that could be supported in the future?

Thanks

**Comment by d3zd3z** [comment]
It indeed is something that might make sense for MCUboot to support in the future. However, it probably won't happen unless an interested party comes forward to do the work.
