### ISSUE TITLE
MCU boot failure on firmwage image failed condition

### ISSUE THREAD

**Issue by 99003662** [mcu-tools/mcuboot#1446]
Hi team,
           I need to know the behavior of mcuboot after firmware image fail condition. 
Consider a scenario, where I have two working image in two slots ( both image are valid and everything is fine). after 4-5 days of running , if my image (which is running in slot0) got corrupted. at this condition does mcuboot will boot the second image which is in slot1 ?

**Comment by nvlsianpu** [comment]
No. Mcuboot will just stop botting your image.

**Comment by 99003662** [comment]
> No. Mcuboot will just stop botting your image.

Thanks for reply @nvlsianpu , is there any way to overcome this ?

**Comment by nvlsianpu** [comment]
What you asking for is problematic as it open a way to atack the device by rollback to older image version (which might contain a bug which was fixed). I'm not sure - but maybe the bootstrap feature might help you, or the direct-xip mode might.
