### ISSUE TITLE
Files with open-source license and proprietary license reference

### ISSUE THREAD

**Issue by rahulmohang** [mcu-tools/mcuboot#1490]
Hi, 

There are multiple files with license approved by OSI as well as license of proprietary nature are referenced together. e.g. 

https://github.com/mcu-tools/mcuboot/blob/main/boot/cypress/MCUBootApp/keys.c.

Can you please let me know which license applies to the files?

If the second license applies too, then the license references a EULA. However, such a EULA is not a part of the source code bundle.

**Comment by alpianon** [comment]
IMHO this part sounds a bit critical:

> If no EULA applies, Cypress hereby grants you a personal, non-
> exclusive, non-transferable license to copy, modify, and compile the
> Software source code solely for use in connection with Cypress's
> integrated circuit products. Any reproduction, modification, translation,
> compilation, or representation of this Software except as specified
> above is prohibited without the express written permission of Cypress.

An express license grant should be provided by Cypress to the MCU Boot project in order to distribute the covered software

**Comment by d3zd3z** [comment]
This does need to be resolved.

**Comment by d3zd3z** [comment]
@romanjoe any chance you can look into this?
