### ISSUE TITLE
MCUboot public API should be better isolated

### ISSUE THREAD

**Issue by d3zd3z** [mcu-tools/mcuboot#1504]
Right now, the MCUboot public API code is compiled outside of MCUboot, and currently requires numerous configuration settings to be made exactly the same as the MCUboot image that is actually in place. This is largely because this code is compiled within Zephyr (or TF-M). This setup is fragile, and in many common configurations ends up being wrong. Some configuration options, on Zephyr, aren't available to this client.

A better solution would be to have this code implemented by MCUboot itself. There is difficulty here, because MCUboot needs flash operations, which in its code would depend on the flash driver in it's own copy of the RTOS. There are also issues with having permission to execute the MCUboot code.

Some ideas would be to make the code general (not depend at all on the underlying configuration) but provide a mechanism to read the configuration from the in-use bootloader.

**Comment by mimok** [comment]
Not sure but I would say that time isolation from ARM PSM would prevent access to mcuboot flash memory from TFM or RTOS. Only shared data shall be accessible. For example, on STM devices this is implemented using HDP mechansim.
