### ISSUE TITLE
How to modify the flash content in mcuboot region

### ISSUE THREAD

**Issue by Sathishkumar-rk** [mcu-tools/mcuboot#1559]
Hi,

Board (i.MXRT1160_EVK).

I want to change the mcuboot flash content in the region [0x30000000:0x30001000] for otfad encryption keyblob value update based on new image upgrade process at **runtime**.

Is it possible to change the content while do run swapping of content from secondary slot to primary slot.

My initial trial is, current image is in primary slot and their keyblob is stored on mcuboot flash area & store the upgrade image on secondary slot with it's keyblob, while doing upgrade i want to copy the keyblob content while trying that I cannot able change content at run time. But primary & secondary slot content is able to swap.

Is that mcuboot flash content is not accessible at run time?

Thanks,
Sathishkumar K

**Comment by de-nordic** [comment]
This should be converted to a discussion.
