### ISSUE TITLE
A fixed slot for mcuboot?

### ISSUE THREAD

**Issue by Huckies** [mcu-tools/mcuboot#1562]
Hi,

Background:
I've written some kind of project made up of a bootloader and an app. The bootloader is responsiable for upgrading app and upgrading alone, in an 'overwrite' pattern. That is, when the app needs to be upgraded, it resets the chip and stays in the bootloader, then the original app is erased, waiting for transmitting a new one.

Now I want to take advantage of security mechanisims of mcuboot, after failing migrating this wonderful repo to the bare metal I use, may I kindly ask a few questions:

1.Is it possible to keep a fixed area in flash to place the mcuboot boot selection code, along with the original bootloader, while only one app partition is set? If the answer is yes, how should I set the flash backend?

2.If the value read back from an erased flash page isn't `0xFF` but another fixed, 4-byte word, is mcuboot ok with that?

Thank you in advance!

**Comment by de-nordic** [comment]
This should be converted to discussion.
