### ISSUE TITLE
Do mcuboot provide samples without OS？

### ISSUE THREAD

**Issue by xuzihan351** [mcu-tools/mcuboot#1572]
HI，
      I am using Mcuboot without OS. I have built mcuboot itself and it can works. I have two questions about mcuboot applications.
      1.Is there samples without OS to refer to?
      2.Applications should call boot_set_confirmed() after it started to make it a permanent upgrade? Otherwise it will revert at next boot?

Thank you,
Shawn Xu

**Comment by FirasSahli2010** [comment]
I am still new to MCUBoot, 
For a new project, I am looking for an example like  this too, 
@xuzihan351 can you provide me with a small instruction or references on how to start

**Comment by utzig** [comment]
Might be helpful: https://interrupt.memfault.com/blog/mcuboot-overview
