### ISSUE TITLE
ESP-IDF 5.0 Support

### ISSUE THREAD

**Issue by vindicatorr** [mcu-tools/mcuboot#1611]
I know the submodule used esp-idf 4.4, but I'd like to see 5.0 brought to the forefront.
I figure there's going to be a bunch of changes, the first of which I'm seeing is `${esp_idf_dir}/components/hal/soc_hal.c` no longer existing.

EDIT0: Weird, how was this ever built for esp-idf anyway? [`${esp_idf_dir}/components/bootloader_support/src/bootloader_efuse_${MCUBOOT_TARGET}.c`](https://github.com/mcu-tools/mcuboot/blob/main/boot/espressif/hal/CMakeLists.txt#L70) doesn't even exist in 4.4. There is no `MCUBOOT_TARGET` variant for `efuse`: https://github.com/espressif/esp-idf/tree/release/v4.4/components/bootloader_support/src.

**Comment by almir-okato** [comment]
Hi @vindicatorr
Yes, we will work to migrate IDF submodule version from 4.4 to 5.0. I hope that I can bring updates soon about this.

Regarding these files `bootloader_efuse_${MCUBOOT_TARGET}.c` you've mentioned, see the tagged [released version](https://github.com/espressif/esp-idf/releases/tag/v4.4): https://github.com/espressif/esp-idf/tree/v4.4/components/bootloader_support/src, the files are there.
