### ISSUE TITLE
How to know what is the active image?

### ISSUE THREAD

**Issue by GiulioDallaVecchia** [mcu-tools/mcuboot#1699]
Hi all,

I'm working on a project where I've set loading mode from RAM. The final application is copied to external RAM and run. I've set two slot on flash: primary and secondary slot. How can I know in which slot there is the active image? I need to know that in order to copy the newest application image to the correct slot.

**Comment by GiulioDallaVecchia** [comment]
Anyone? 

I'm not using DirectXIP mode, but RAMLOAD mode. With this mode the newer image will be executed. I need to know where is the newer image (slot 1 or 2?) in order to understand what is the slot that I can erase when I have to upload a new image.

Thanks a lot!

**Comment by nordicjm** [comment]
From the image running itself? You can use shared boot data to get the current running image number and then use that to determine which slot to erase from the application.

**Comment by abdulafroz04** [comment]
Can you provie me a detailed procedure of making a signed application binary using ther imgtool.
