### ISSUE TITLE
New downgrade prevention mechanism bypassable

### ISSUE THREAD

**Issue by ghost** [mcu-tools/mcuboot#1708]
The new parameter `MCUBOOT_DOWNGRADE_PREVENTION_SECURITY_COUNTER` has been added half year ago to use the security counter instead of the actual version of software for software downgrade prevention Modifications come from this commit:
https://github.com/mcu-tools/mcuboot/commit/e3f895d7ef8304a8c87f4cb85bd5552cb68d61df.

However this countermeasure in only effective when `TEST` mode is used. Downgrade is possible in `REVERT` or `CONFIRM` mode.

https://github.com/mcu-tools/mcuboot/blob/eb7658e84c09e69c008332ed0163d8f91769ef00/boot/bootutil/src/loader.c#L2111-L2121

When this mode is enabled downgrade is trivial. Is it a bug or do I miss something ?

Best regards

**Comment by trustngotech** [comment]
Any news ? Seems to be quite problematic no ? Do you want I propose a PR to speed up the process ?

**Comment by kasjer** [comment]
My understanding was that new image can be place in slot1 and marked as test image with version increased.
If mcuboot swapped images, image with higher version is executed but if it is not confirmed by application (for example it crashes) revert to lower version that actually worked should be a valid case.

**Comment by trustngotech** [comment]
@kasjer You are right and my PR still allows revert when there is a problem with the new firmware. However, your code allows to bypass the rollback check when an already confirmed image is sent to the device. This is why i proposed to move the check from the TEST case to the PERM case (with falltrough between them).

**Comment by kasjer** [comment]
@trustngotech I did not seen PR in time, everything looks good. In my case it was not possible to send already confirmed image. Application had to start first and then after some communication image was confirmed after swap.
Thanks for correcting this.

**Comment by trustngotech** [comment]
By doing some clean-up is mistakenly deleted the previous repo and thus the attached pull request which was still not merged. Sorry for the inconvenience.
