### ISSUE TITLE
docu uses KCONFIG symbol that does not exist for downgrade prevention

### ISSUE THREAD

**Issue by ChrisKurz** [mcu-tools/mcuboot#1713]
Hi,
I think there is a inconsistency in the docu... The chapter "Software-based downgrade prevention" about Downgrade prevention talks about:
"... In this case downgrade prevention is only available when the overwrite-based image update strategy is used (i.e. MCUBOOT_OVERWRITE_ONLY is set). ..."
https://github.com/mcu-tools/mcuboot/blob/main/docs/design.md#software-based-downgrade-prevention

But the KCONFIG symbol MCUBOOT_OVERWRITE_ONLY does not exist. I think the correct symbol is BOOT_UPGRADE_ONLY, as defined in 
https://github.com/mcu-tools/mcuboot/blob/9ced459b09f39d94b8770817ae4c78f520c2a679/boot/zephyr/Kconfig#LL218C8-L218C25.

**Comment by nordicjm** [comment]
The documentation is correct, you are mixing up the MCUboot define with the zephyr Kconfig name, they are not the same.
