### ISSUE TITLE
Reboot and force mcuboot to stay in boot mode

### ISSUE THREAD

**Issue by pwilkowski** [mcu-tools/mcuboot#1729]
Hello, I have heard this is possible however i have not found any examples, if so, how can i achieve it with simplest program possible?
ex.

```c
void main(void)
{
	printk("Hello World! %s\n", CONFIG_BOARD);
	// set mcuboot flag of some sort to force it to never go to program?
	sys_reboot();
}

```

**Comment by pepe2k** [comment]
Hi @pwilkowski, you didn't provide much information in you question (e.g. what OS and platform you are using) but in case of Zephyr, have a look at options `BOOT_SERIAL_PIN_RESET` (35941feacd0650bc3e7dc72e7490d589367d553c) and `BOOT_SERIAL_BOOT_MODE` (b3e3ce39f3e1abd95ff4010263b3613edf59dd54). Hope that helps!
