### ISSUE TITLE
Compiler Warning in bootutil_max_image_size due to Incorrect Argument Type

### ISSUE THREAD

**Issue by tbitcs** [mcu-tools/mcuboot#1860]
### Environment
MCUboot Version: [V2.0.0](https://github.com/mcu-tools/mcuboot/commit/304fd41980ed929533b9f387dde1b463b0be5b90) and [0c0470e](https://github.com/mcu-tools/mcuboot/tree/0c0470e294dcfb52aab92299356a5f3caa0aa52b)
Compiler/Toolchain: GNU Tools for Arm Embedded Processors 7-2018-q2-update 7.3.1 20180622 (release)

### Issue
When building MCUboot, a compiler warning is generated in the [`bootutil_max_image_size`](https://github.com/mcu-tools/mcuboot/blob/0c0470e294dcfb52aab92299356a5f3caa0aa52b/boot/bootutil/src/bootutil_misc.c#L341C31-L341C31) function:

`passing argument 1 of 'flash_area_get_sectors' makes integer from pointer without a cast [-Wint-conversion]`

This occurs in the following code segment:

```
#ifdef MCUBOOT_SWAP_USING_MOVE
    struct flash_sector sector;
    int rc = flash_area_get_sectors(fap, boot_status_off(fap), &sector);
    ...
#endif
```

In addition, argument 1 is also incorrect as it should use `fap->fa_id` instead of `fap`. When the previous issue is fixed, the following warning is now present:

`passing argument 2 of 'flash_area_get_sectors' makes pointer from integer without a cast [-Wint-conversion]`

### Expected Behavior
The code should pass a pointer to `uint32_t` to `flash_area_get_sectors` without causing a compiler warning.
The code should pass `fap->fa_id` to `flash_area_get_sectors` without causing a compiler warning.

### Actual Behavior
Compiler warning due to incorrect argument types, potentially leading to undefined behavior at runtime.

### Steps to Reproduce
1. Configure MCUboot with `MCUBOOT_SWAP_USING_MOVE` defined.
2. Compile the MCUboot source code.
3. Observe the compiler warning related to [`bootutil_max_image_size`](https://github.com/mcu-tools/mcuboot/blob/0c0470e294dcfb52aab92299356a5f3caa0aa52b/boot/bootutil/src/bootutil_misc.c#L341C31-L341C31).

### Suggested Fix
Review and update the arguments are passed to `flash_area_get_sectors`. This might involve the following:
1. Replacing `boot_status_off(fap)` with a dummy pointer. Or as another solution, `boot_status_off(fap)` could be replaced with a NULL pointer and the `flash_area_get_sectors` implementation could be updated to ignore returning `total_count` to `count` if it's NULL.
2. Replace `fap` with `fap->fa_id` to `flash_area_get_sectors`

**Comment by thedjnK** [comment]
This doesn't make sense, the file you have linked uses `flash_area_get_sector()` and not `flash_area_get_sectors()`, seemingly you have local modifications.

**Comment by tbitcs** [comment]
> This doesn't make sense, the file you have linked uses `flash_area_get_sector()` and not `flash_area_get_sectors()`, seemingly you have local modifications.

After reviewing the documentation for MCUboot 2.0.0, I realized that it necessitates the integration of the `flash_area_get_sector` API into the platform's implementation. Implementing this API successfully addressed the previously encountered issues. The confusion arose due to a misunderstanding on my part, which has now been rectified.
