### ISSUE TITLE
it_tlv_tot is uint16_t and also it_len

### ISSUE THREAD

**Issue by Tomerzahavi** [mcu-tools/mcuboot#1871]
If the sum of several TLV it_lens exceeds 64K, how can we indicate it_tlv_tot in the TLV info?

**Comment by nordicjm** [comment]
Why would you have > 64KiB of TLV data? If you are using zephyr, you could make use of the binary descriptor feature instead which would allow for arbitrary length values

**Comment by de-nordic** [comment]
@Tomerzahavi  That is not a bug report, seems like topic for discussion. Convert do discussion or elaborate on what you expect.
Marking to be closed after 23.03.2024 if no action till then.
