### ISSUE TITLE
MCUBOOT_BOOTSTRAP meaning with/without MCUBOOT_VALIDATE_PRIMARY_SLOT

### ISSUE THREAD

**Issue by Rehan-MALAK** [mcu-tools/mcuboot#1887]
I posted the message below, Friday 12th on the mailing list
https://groups.io/g/mcuboot/message/86
Maybe maintainers would prefer to answer here or to go to "github discussion". Let's see.

##############################

Dear all,

I am currently experimenting with authentication algorithms in MCUBoot and could use a bit of help understanding these build options :
- `MCUBOOT_BOOTSTRAP`
- `MCUBOOT_VALIDATE_PRIMARY_SLOT`
and the implications for how often one validates a slot (boot_validate_slot()) and which one(s) ?

Would really appreciate your insights on this :) !

[docs/design.md](https://github.com/mcu-tools/mcuboot/blob/main/docs/design.md) says this about `MCUBOOT_VALIDATE_PRIMARY_SLOT`
    _"An image is checked for integrity immediately before it gets copied into the
    primary slot.  If the bootloader doesn't perform an image swap, then it can
    perform an optional integrity check of the image in the primary slot if
    `MCUBOOT_VALIDATE_PRIMARY_SLOT` is set, otherwise it doesn't perform an
    integrity check."_

[docs/design.md](https://github.com/mcu-tools/mcuboot/blob/main/docs/design.md) doesn't say anything about `MCUBOOT_BOOTSTRAP`

One can read this in [boot/nuttx/include/mcuboot_config/mcuboot_config.h](https://github.com/mcu-tools/mcuboot/blob/main/boot/nuttx/include/mcuboot_config/mcuboot_config.h)  :
    _"Enable bootstrapping the erased primary slot from the secondary slot"_
but I don't understand this last sentence (and specifically what is the meaning of "bootstrap" here)

[docs/design.md](https://github.com/mcu-tools/mcuboot/blob/main/docs/design.md) gives some explanation on the four iterations over all the images in [boot/bootutil/src/loader.c:context_boot_go()](https://github.com/mcu-tools/mcuboot/blob/main/boot/bootutil/src/loader.c#L2008)
and particularly where are the two eventual "integrity and security check" (I will call them from now on "loop1" and "loop4")

Let's suppose I have this :
- `MCUBOOT_IMAGE_NUMBER` = 1 (so no dependency between images)
- `MCUBOOT_ENC_IMAGE` = Off
- `MCUBOOT_OVERWRITE_ONLY` upgrade strategy

After erasing the flash memory entirely, I flash a signed firmware in the slot 2.

What I see currently is this behavior :

![table](https://github.com/mcu-tools/mcuboot/assets/39339802/6e7ad5a2-79fe-4696-aef3-dd269130ad18)

Can you reproduce this and is this the intended behavior ?

Case 2 seems to be exactly what I'm looking for, but I want to ensure that setting MCUBOOT_BOOTSTRAP = Off is indeed the correct approach.

Thanks a lot for your help.
Best regards,

Rehan MALAK

**Comment by physicsboy0709** [comment]
Hi, can you give more information about the macro MCUBOOT_BOOTSTRAP?
