### ISSUE TITLE
Where can I download MCUBoot documents in pdf format?

### ISSUE THREAD

**Issue by snowuyl** [mcu-tools/mcuboot#1924]
I can find some MCUBoot documents from https://github.com/mcu-tools/mcuboot/tree/main/docs. But these documents are not in pdf format. Where can I download MCUBoot documents in pdf format?

**Comment by nordicjm** [comment]
There is no PDF documentation, there is web documentation on https://docs.mcuboot.com/

**Comment by snowuyl** [comment]
Thanks for your reply!
