### ISSUE TITLE
How to put mcuboot in external NOR flash?

### ISSUE THREAD

**Issue by snowuyl** [mcu-tools/mcuboot#1930]
I would like to put mucboot in external NOR flash for saving internal flash of SoC storage. Do mcuboot team provide document about how to put mcuboot in external NOR flash for Zephyr platform?

**Comment by nordicjm** [comment]
No, this would be down to you to design in dts. Your device would need to support memory mapping of the external flash device and be able to do that with a persistent configuration i.e. without code executing on internal flash to set that up (or you would need to design said internal flash application that does that and jumps to the MCUboot reset vector)

**Comment by snowuyl** [comment]
Thanks for your reply!
