### ISSUE TITLE
Unnecessary if-statement in boot_serial.c

### ISSUE THREAD

**Issue by robertpaananen** [mcu-tools/mcuboot#1940]
https://github.com/mcu-tools/mcuboot/blob/93c3f78b850989618646c0094fae09da329616fa/boot/boot_serial/src/boot_serial.c#L1166-L1175

Currently trying to implement serial recovery over uart and noticed some weird things in this code. Am I crazy or is the second if-statement unnecessary? When debugging it seems like the complier removes it.

**Comment by nordicjm** [comment]
Looks useless to me, feel free to submit a PR removing it
