### ISSUE TITLE
Timeout in boot_serial_read_console not working properly

### ISSUE THREAD

**Issue by eskowitz-adi** [mcu-tools/mcuboot#1991]
I believe there is a bug in the way timeouts are measured in boot_serial_read_console.

The function contains a while loop that continues looping as long as the timeout argument timeout_in_ms is greater than 0

while (timeout_in_ms > 0 || bs_entry)

Inside of the loop the timeout argument is decreased on each iteration

timeout_in_ms -= elapsed_in_ms;

Decreasing the timeout period on each iteration will lead to a timeout faster than the desired millisecond count.  Instead I believe that the while loop should be

while(timeout_in_ms >= elapsed_in_ms || bs_entry)

and the value of timeout_in_ms should not be changed in the body of the loop.

**Comment by nordicjm** [comment]
I don't see an issue, if you do not do the wait in DFU mode then timeout is never decremented which is expected. If you are in timeout mode then the following happens on each loop:
```
    while (timeout_in_ms > 0 || bs_entry) {
...
        uint32_t start = k_uptime_get_32();
...
        elapsed_in_ms = (k_uptime_get_32() - start);
        timeout_in_ms -= elapsed_in_ms;
```
So `elapsed_in_ms` is the elapsed time in ms between the start and end of the loop, where is the issue?
