### ISSUE TITLE
[Swap without scratch] no boot happens if secondary image is not readable

### ISSUE THREAD

**Issue by kica-z** [mcu-tools/mcuboot#2001]
Hello

We are currently facing a problem with our device. On our device it is possible that the secondary partition is not available during a boot. In theory this should not be a problem since the primary partition remains functional and would be boot-able. In reality however this leads to mcuboot not booting either image since the secondary flash area cannot be opened. Error: `Failed to open flash area ID ...` ([bootutil/src/loader.c:2144](https://github.com/mcu-tools/mcuboot/blob/fb2cf0ec3da3687b93f28e556ab682bdd4b85223/boot/bootutil/src/loader.c#L2144C31-L2144C59)).

The question would now be how to proceed. So we have some questions:
- Is this intended behaviour? If yes what is the reasoning behind it?
- Can/Should this be adjusted?

**Comment by nordicjm** [comment]
This is expected behaviour, if your secondary slot can just vanish, that sounds like a pretty big hardware design problem

**Comment by kica-z** [comment]
Hi Jamie, thanks for the response.
That is a fair assumption/limitation. I would however not go as far as to call this a hardware design problem. Be that as it may since this is expected behavior i will close this issue as the question has been answered.
