### ISSUE TITLE
Protect bootloader flash pages as much as possible

### ISSUE THREAD

**Issue by d3zd3z** [mcu-tools/mcuboot#206]
Some devices have flash page protection, but it is transient, and needs to be initialized on every boot. Add platform hooks to mcuboot so that these can be added for these platforms to protect the bootloader memory from being written. This should be done as early as possible in the instruction stream.

**Comment by nvlsianpu** [comment]
nRF5 devices have dedicated HW:
- BPROT (Block protection): nRF51/nRF52832
- ACL (Access control lists): nRF52840 ACL 

I think  reasonable approach here i  creating backend for flash protection in zephyr. This would be an API extension to the flash driver, wrraped by flash_map abstraction as well.

cc @carlescufi
