### ISSUE TITLE
Always use overwrite-only code for non-revert upgrades

### ISSUE THREAD

**Issue by d3zd3z** [mcu-tools/mcuboot#207]
We have added the configuration BOOTUTIL_OVERWRITE_ONLY to allow a simpler upgrade process to be used. Instead of just making this code a compile-time choice, enhance the regular startup to use this code when the system has requested a non-test upgrade (which won't be reverted).

Since there is still a desire to be able to revert, this should be another compilation option.

**Comment by d3zd3z** [comment]
Copied from JIRA [MCUB-57](https://runtimeco.atlassian.net/browse/MCUB-57).

**Comment by mbolivar** [comment]
MCUboot is pretty near to its flash partition size (with debug logging enabled) on various targets right now. This might put it over -- just FYI
