### ISSUE TITLE
Add common hardware security support, including MPU and HSM

### ISSUE THREAD

**Issue by aditihilbert** [mcu-tools/mcuboot#219]
HW features include, but are not limited to: 

OTP memory for secure key storage 
crypto accelerator 
TCB (trusted computing base) e.g. ROM 
isolated execution environment 
device authentication - immutable base identity 
execution-aware memory protection unit

This issue covers adding support for HSM to MCUboot (likely to imgtool). It will probably be needed to do some initial investigation as to what HSM to initially support. Without an economical device, we may have to leave the support simulated, with hooks, so that someone needing these devices can add the support.

**Comment by d3zd3z** [comment]
We should probably make separate issues for the ones we wish to support. I'll create one for HSM.
