### ISSUE TITLE
Remove padding for ECDSA signatures

### ISSUE THREAD

**Issue by aditihilbert** [mcu-tools/mcuboot#220]
Now that the header no longer contains the TLV size, it is not necessary to pad the value used for an ECDSA signature. These signatures can vary slightly in size, depending on the setting of the highest bit (they are encoded as signed integers, which if the high bit is set, will cause an extra 0x00 byte to be emitted). 

However, imgtool.py and the verification code still have support for this padding. We probably can't remove the code that verified from allowing the padding, since that would break parsing of existing signatures, but we can change imgtool to no long add the padding.

**Comment by d3zd3z** [comment]
imgtool no longer pads.
