### ISSUE TITLE
Remove force interrupt enabling for Zephyr

### ISSUE THREAD

**Issue by carlescufi** [mcu-tools/mcuboot#302]
In [`boot/zephyr/serial_adapter.c`](https://github.com/mcu-tools/mcuboot/blob/f2ac70db184548a447945dde470ceed855e31107/boot/zephyr/serial_adapter.c) we are currently enabling interrupts due to an issue in the upstream Zephyr: https://github.com/zephyrproject-rtos/zephyr/issues/8393. Remove that once the upstream issue is fixed.

**Comment by carlescufi** [comment]
CC @nvlsianpu

**Comment by sigvartmh** [comment]
Can this be removed as https://github.com/zephyrproject-rtos/zephyr/pull/9668 is merged?

**Comment by carlescufi** [comment]
No, because it was reverted here: https://github.com/zephyrproject-rtos/zephyr/pull/9829

**Comment by sigvartmh** [comment]
I see.

**Comment by d3zd3z** [comment]
Any status updates here? Do we need to push a fix into Zephyr?

**Comment by carlescufi** [comment]
@d3zd3z we need the equivalent of zephyrproject-rtos/zephyr#9668, which was merged but then reverted
