### ISSUE TITLE
Constrained devices don't build out-of-the-box with Zephyr

### ISSUE THREAD

**Issue by SebastianBoe** [mcu-tools/mcuboot#433]
Constrained devices don't build out-of-the-box with Zephyr.

For instance, bbc_microbit doesn't build.

We have solved this for specific boards, e.g. #411 .

But now that DT symbols can be accessed from Kconfig, it should be possible to turn off unnecessary features based on FLASH / RAM size and solve this generally.

**Comment by d3zd3z** [comment]
Is disabling logging typically enough for this? Not having logging on does make MCUboot more difficult to debug, though. Can we solve this by means other than documentation? e.g. Is there a mechanism to have board-specific Kconfigs in the app directory (like we do with device tree overlays)?

**Comment by SebastianBoe** [comment]
>  e.g. Is there a mechanism to have board-specific Kconfigs in the app directory

Yes, see for instance https://github.com/JuulLabs-OSS/mcuboot/pull/412/files

but it would scale better to use generic DT information like flash and ram size to set Kconfig options. This is possible by defining a new Kconfig root with additional intializations of the options that depend on DT size information.
