### ISSUE TITLE
chain-load the application via Reset

### ISSUE THREAD

**Issue by nvlsianpu** [mcu-tools/mcuboot#668]
objective: introduce  mechanism which allow to enter the application in the clean state as signaled in #529

possible solution:
Introduce execution flow in which mcuboot chain-load the application via reset.
Need to introduce a very early executed code partition which allows to recognize whether start to execute bootloader or the application.

some context form #665  by @nordic-krch:
>I assume that bootloader simply jumps to the application, right? If so then i'm a bit afraid about what happens with system clock which is running (RTC) and will expire after jumping to the application. For application kernel that will be confusing and may lead to serious, hard to detect issues.

> I don't know mcuboot details but imo jumping to the application from bootloader should always happen after reset (with clean state). There are some resources started (usb, clock, rtc, mpu?, etc.) and application is not expecting that.

> It's not about validation of the application. That should be performed before jump to application or omitted only on user responsibility, e.g. after special reset like wakeup from deep sleep. From my experience with the bootloader it nrf5 sdk, there should be no direct jump to the application once bootloader performed any actions other than the one needed to start application. That is image update or recovery. It's usually quite difficult to get back to clean state and reset is the safest and simplest way.

**Comment by utzig** [comment]
The challenge would be to avoid breaking test/revert flow. For other upgrade methods should be "easy" (or easier at least).

**Comment by nvlsianpu** [comment]
^^ Decision what to execute should be done very early, before any image touch, so shouldn't affect even test/reset flow i believe. Just need to find some reliable way (software triggered resed prof) to recognize what should be executed.

**Comment by d3zd3z** [comment]
Short of actual hardware support for this, the only thing I can think of is to put particular patterns in RAM. The trick is getting to only do this once (so I guess it should clear the pattern before then jumping to the app).
