### ISSUE TITLE
Boot Status Offset not calculated correctly always

### ISSUE THREAD

**Issue by solsbarry** [mcu-tools/mcuboot#777]
https://github.com/JuulLabs-OSS/mcuboot/blob/505c6e6ac493555483cd50056c1ed051975729c1/boot/bootutil/src/bootutil_misc.c#L200

So in the situation where the primary partition is in a different flash area than the scratch and the secondary partitions. And when the flash device the primary partition is in has a different minimum write size than the flash device containing the scratch partition. You run into an issue.

The function `boot_status_off `calculates the an offset based on the min write size of the partition (via `flash_area_align(fap)`). But the the function `swap_read_status_bytes` tries to read the swap status by iterating through the status section `BOOT_WRITE_SZ(state)` bytes at a time. In the scenario I described above, `BOOT_WRITE_SZ(state)` can be different than `flash_area_align(fap)`.  

so if the scratch flash has a min write size of 4. and the primary image flash has a min write size of 1.
`BOOT_WRITE_SZ(state)` will be 4,
and 
`flash_area_align(fap)` will be 1 for the primary partition.

thus the attempt to read flash here
https://github.com/JuulLabs-OSS/mcuboot/blob/505c6e6ac493555483cd50056c1ed051975729c1/boot/bootutil/src/swap_scratch.c#L113
will eventually read past the end of flash.

So I think the function to determine the status offset should be based on the largest  min write size of all the flash devices involved, because that is what is done elsewhere.

the variable `state` is available every time `boot_status_off` is used, so you should be able to just pass it in to that fucntion instead of finding the value inside the function.

**Comment by utzig** [comment]
Sounds like a fair assessment. The reason scratch should live in internal flash is because when using encrypted images, they are stored un-encrypted on scratch, so one could attack the upgrade operation to recover the original image. If not using encrypted images, it'd be OK to have scratch in external flash. Feel free to submit a PR.
