### ISSUE TITLE
Zephyr: Use of deprecated CONFIG_MULTITHREADING

### ISSUE THREAD

**Issue by JordanYates** [mcu-tools/mcuboot#820]
`/boot/zephyr/Kconfig` conditionally defaults `CONFIG_MULTITHREADING` to `n`.
This configuration option has been deprecated in Zephyr 2.4 and results in warnings.
https://github.com/zephyrproject-rtos/zephyr/pull/27988

**Comment by jadonk** [comment]
*ugh*
