### ISSUE TITLE
zephyr: disable HW stack protection before run application

### ISSUE THREAD

**Issue by nvlsianpu** [mcu-tools/mcuboot#833]
This ticket is for tracking the problem. The issue is considered to be resolved in zephyr-rtos code.

Zephyr might enable HW stack protection by default, which
propagates in mcuboot build. Bootloader works fine with that option, but
the problem arises when we jump to application code.

HW stack protection catches application code during early init, which results in
"unresponsive" application.

So fare issue is hidden thanks to #828 hack

- [x] support ARM leverages SPLIM devices (Cortex M33...) ref: #824
- [x] support ARM leverages MPU devices

**Comment by mniestroj** [comment]
I think we should have some generic API for disabling HW stack protection, possibly in Zephyr, then use it in mcuboot. Implementation details such as that implemented in #824 should be hidden in `arch/` directory.

**Comment by nvlsianpu** [comment]
__weak void z_arm_clear_arm_mpu_config(void) from https://github.com/mcu-tools/mcuboot/pull/847 supports ARM leverages MPU devices. Also zephyr introduces https://github.com/zephyrproject-rtos/zephyr/pull/29400 so mcuboot won't need to cleanup register if application will use this functionality.
