### ISSUE TITLE
imgtool --confirm doesn't work if output file is Intel Hex files.

### ISSUE THREAD

**Issue by nvlsianpu** [mcu-tools/mcuboot#861]
`imgtool sign build/hellow_single/zephyr/zephyr.hex  my_signed.hex --align 8 -H 0x200 -S 0xe8000 -k ./bootloader/mcuboot/root-rsa-2048.pem -v 1.2.3 --pad --confirm`

If output is `*.bin` command works correctlly

I've used version v1.6.0

**Comment by romanjoe** [comment]
HI, this is fixed in recent master. PR for this fix https://github.com/mcu-tools/mcuboot/pull/806
