### ISSUE TITLE
License headers and SPDX identifiers missing

### ISSUE THREAD

**Issue by jainvikas8** [mcu-tools/mcuboot#930]
I have comes across License header and SPDX identifiers missing on most of these https://github.com/mcu-tools/mcuboot/tree/master/scripts

Wonder if this can be fixed, please?

**Comment by jainvikas8** [comment]
I don't think #933 fixes both the issues here.

Copyright/License header is still missing, please that be added to?

**Comment by d3zd3z** [comment]
What are you finding still missing? In general, most open source projects have determined that an SPDX license is sufficient as a license marking. As far as copyright markings, I'm not really able to add those for entities other than my own employee, so if people feel they need to add them, they would have to do that themselves.
