### ISSUE TITLE
Why mcuboot ram load not support  image decryption?

### ISSUE THREAD

**Issue by Cherish-forever** [mcu-tools/mcuboot#944]
I have read mcuboot design guide, I am not understand why ram load not support image decryption?
In image slot mode or direct-xip mode, there always have some method to attacks flash.
exp:
1. read all flash
2. write a boot image jump to image slot
3. merge boot and image slot as a compound binary
4. burn to MCU

Here is detail from design.html:
Usually in this case the images are stored in an external storage device. Execution from external storage has some drawbacks (lower execution speed, image is exposed to attacks) therefore the image is always copied to the internal RAM before the authentication and execution. 
The ram-load mode currently supports only the single image boot and the image encryption feature is not supported.

image slot mode or direct-xip mode, the firmware is exposed.
if ram load support image encryption. the image in flash is encryption.
if need run firmware, mcuboot must decryption the flash and load to ram, even if firmware has been read , it is encryption, generate boot just jump is no use.

**Comment by Cherish-forever** [comment]
In ram load mode, two slot mode need encryption, ram load can support multiple encryption, not only one.

**Comment by d3zd3z** [comment]
Fairly simple reason: it hasn't been implemented yet. I believe someone is working on this, however.
