### ISSUE TITLE
How to encrypt binary body, not only sign

### ISSUE THREAD

**Issue by Cherish-forever** [mcu-tools/mcuboot#969]
I am running 
`$ ./bootloader/mcuboot/scripts/imgtool.py sign --key bootloader/mcuboot/root-rsa-2048.pem --header-size 0x200 -S 0x20000 --align 8 --version 1.3 -E build_space/hello_world/black_f407zg_pro/zephyr/zephyr.hex signed-zephyr-1.3.hex`

and I found that binary body does not encrypt, only add a header and tail, but body in middle was not encrypt.
what should I encrypt the binary body(code and data).

**Comment by utzig** [comment]
You must pass a public key to `-E`, no the firmware file.

**Comment by Cherish-forever** [comment]
@utzig add  -E bootloader/mcuboot/root-rsa-2048.pem ?

**Comment by Cherish-forever** [comment]
@utzig 
it works
Thank you very much,  but I don`t understand why encrypt do not use --key bootloader/mcuboot/root-rsa-2048.pem file?

**Comment by Cherish-forever** [comment]
@utzig 
Thank you very much, I have encrypt firmware by adding -E parameter.
but, I found after encrypted, images sha256 verify failed.
sign key is different with  body encrypt key, but the same kind of encrypt type.
