### ISSUE TITLE
boot_go() Returns boot_version_cmp() Value 

### ISSUE THREAD

**Issue by sjgiewont** [mcu-tools/mcuboot#976]
`boot_go()` and consequently `context_boot_go()` will return a `boot_version_cmp()` return value if no pre-compile features are defined (MCUBOOT_DIRECT_XIP_REVERT, MCUBOOT_RAM_LOAD, MCUBOOT_HW_ROLLBACK_PROT, MCUBOOT_MEASURED_BOOT, MCUBOOT_DATA_SHARING). 

`boot_version_cmp()` returns -1, 0 or 1 to imply version comparison results. These values can be incorrectly interpreted as a non-zero error code when returned from `boot_go()`. 

https://github.com/mcu-tools/mcuboot/blob/986c212ea902e2c58bce5860195db605684edf7f/boot/bootutil/src/loader.c#L2347-L2348

**Comment by AGlass0fMilk** [comment]
I am also encountering this issue on Mbed-OS. My configuration is direct XIP (no revert), without any signature (just SHA256).
