### ISSUE TITLE
the mcuboot code(bin) be placed in a non-flash location ???

### ISSUE THREAD

**Issue by hongshui3000** [mcu-tools/mcuboot#977]
Can the mcuboot code be placed in a non-flash location? I use zephyr to develop and hope to solidify the mcuboot code into the rom (not flash) of my microcontroller

**Comment by nvlsianpu** [comment]
Yes. MCUboot own location is something independent from application images location. MCUboot doesn't write anything to its location. Se no obstacles.

**Comment by hongshui3000** [comment]
@nvlsianpu 
Thanks for the response

![image](https://user-images.githubusercontent.com/25566498/114644420-10155780-9d0a-11eb-8acf-fc93948bc299.png)
From the documentation, "boot_partition: for MCUboot itself" seems to have to be defined. I don't want to put it on the flash partition.

In the other way, I only want to place part of the mcuboot (Bluetooth OTA part) on the flash partition, whether it can perceive and integrate well with the mcuboot part of my rom
