### ISSUE TITLE
switch cbor encoding to generated by cddl-gen

### ISSUE THREAD

**Issue by nvlsianpu** [mcu-tools/mcuboot#978]
Serial recovery mcumgr protocol implementation uses parser generated by cddl-gen while encoding uses tinycbot.
Since a while cddl-gen supports encoder generation which can be leveraged.

Expected results is flash footpint reduction and remove dependence from tinycbor library.

https://github.com/NordicSemiconductor/cddl-gen

**Comment by nvlsianpu** [comment]
@oyvindronningstad Can you take this?

**Comment by oyvindronningstad** [comment]
Yes, I've been looking into it already.

**Comment by carlescufi** [comment]
> Yes, I've been looking into it already. You can assign me, I don't have permissions to do it myself :).

I just assigned you, thanks @oyvindronningstad.

**Comment by de-nordic** [comment]
In progress here: https://github.com/mcu-tools/mcuboot/pull/997
